spring:
  application:
    name: bank-account-api
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: 3880
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/master.yaml

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
